#### Import Libraries

In [1]:
import pandas as pd

In [2]:
credits = pd.read_csv("tmdb_5000_credits.csv")
movies =  pd.read_csv("tmdb_5000_movies.csv")

In [3]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   str
 2   cast      4803 non-null   str
 3   crew      4803 non-null   str
dtypes: int64(1), str(3)
memory usage: 33.8 MB

In [4]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 5.4 MB

In [5]:
movies = movies[["id","genres","keywords","title","tagline","overview","production_companies"]]
credits = credits[["movie_id","cast","crew"]]
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
dtypes: int64(1), str(6)
memory usage: 4.1 MB

In [6]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   cast      4803 non-null   str
 2   crew      4803 non-null   str
dtypes: int64(1), str(2)
memory usage: 33.7 MB

In [7]:
# Lets join both dataframes
# how = 'inner' Keeps only matching rows from both DataFrames.If a row doesn’t match in either table → it gets removed.
df = pd.merge(movies, credits, left_on='id', right_on='movie_id', how='inner')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
 7   movie_id              4803 non-null   int64
 8   cast                  4803 non-null   str
 9   crew                  4803 non-null   str
dtypes: int64(2), str(8)
memory usage: 37.8 MB

In [9]:
df = df.drop(columns = ["movie_id"])

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    4803 non-null   int64
 1   genres                4803 non-null   str
 2   keywords              4803 non-null   str
 3   title                 4803 non-null   str
 4   tagline               3959 non-null   str
 5   overview              4800 non-null   str
 6   production_companies  4803 non-null   str
 7   cast                  4803 non-null   str
 8   crew                  4803 non-null   str
dtypes: int64(1), str(8)
memory usage: 37.7 MB

In [11]:
desc = df.loc[2, 'genres']

In [12]:
desc

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 80, "name": "Crime"}]'

In [13]:
# import json
# import pandas as pd

# def extract_names(text):
#     data = json.loads(text)
#     df = pd.json_normalize(data)
#     return " ".join(df['name'])

import ast
names = []
x = ast.literal_eval(desc)
for item in x:
    names.append(item['name'])

comma_desc = ','.join(names)
comma_desc

'Action,Adventure,Crime'

In [14]:
# df.sample()

In [15]:
import ast
def get_names(desc):
    names = []
    x = ast.literal_eval(desc)
    for item in x:
        names.append(item['name'])
    
    comma_desc = ','.join(names)
    return comma_desc

In [16]:
df['genres'] = df['genres'].apply(get_names)

In [17]:
df['genres']

0       Action,Adventure,Fantasy,Science Fiction
1                       Adventure,Fantasy,Action
2                         Action,Adventure,Crime
3                    Action,Crime,Drama,Thriller
4               Action,Adventure,Science Fiction
                          ...
4798                       Action,Crime,Thriller
4799                              Comedy,Romance
4800               Comedy,Drama,Romance,TV Movie
4801
4802                                 Documentary
Name: genres, Length: 4803, dtype: str

In [18]:
df.sample()

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
1297,64807,Comedy,"[{""id"": 494, ""name"": ""father son relationship""...",Grudge Match,DeNiro vs Stallone,A pair of aging boxing rivals are coaxed out o...,"[{""name"": ""Gerber Pictures"", ""id"": 975}, {""nam...","[{""cast_id"": 1, ""character"": ""Billy 'The Kid' ...","[{""credit_id"": ""562f55819251410a22008d15"", ""de..."

In [19]:
df['keywords'] = df['keywords'].apply(get_names)
df['production_companies'] = df['production_companies'].apply(get_names)
df['cast'] = df['cast'].apply(get_names)
df['crew'] = df['crew'].apply(get_names)

In [20]:
df.sample()

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
206,18823,"Adventure,Fantasy,Action","hades,mythology,greek mythology,zeus,medusa,my...",Clash of the Titans,Titans will clash.,"Born of a god but raised as a man, Perseus is ...","The Zanuck Company,Legendary Pictures,Thunder ...","Sam Worthington,Liam Neeson,Ralph Fiennes,Gemm...","Lucinda Syson,Anna Pinnock,Lynn Harris,Neil Co..."

In [21]:
#need to replace space by '-' in production_companies, cast, crew because we want to treat them as single word while creating bag of words. 
# For example, if we have production company name as "Warner Bros", we want to treat it as "Warner-Bros" instead of two separate words "Warner" and "Bros". 
# So that we can get better recommendations.
    
df['genres'] = df['genres'].str.replace(' ', '-')
df['keywords'] = df['keywords'].str.replace(' ', '-')
df['production_companies'] = df['production_companies'].str.replace(' ', '-')
df['cast'] = df['cast'].str.replace(' ', '-')
df['crew'] = df['crew'].str.replace(' ', '-')

In [22]:
df.sample()

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
1491,13460,"Action,Thriller,Science-Fiction","dystopia,quarantine,futuristic,sword-fight,let...",Doomsday,Mankind has an expiration date.,A lethal virus spreads throughout the British ...,"Rogue-Pictures,Intrepid-Pictures,Scion-Films,M...","Rhona-Mitra,Bob-Hoskins,Malcolm-McDowell,Alexa...","Peter-McAleese,Rob-Inch,Peter-Burgis,Tyler-Bat..."

In [23]:
df.fillna(" ",inplace = True)

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew
0,19995,"Action,Adventure,Fantasy,Science-Fiction","culture-clash,future,space-war,space-colony,so...",Avatar,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...","Ingenious-Film-Partners,Twentieth-Century-Fox-...","Sam-Worthington,Zoe-Saldana,Sigourney-Weaver,S...","Stephen-E.-Rivkin,Rick-Carter,Christopher-Boye..."
1,285,"Adventure,Fantasy,Action","ocean,drug-abuse,exotic-island,east-india-trad...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","Captain Barbossa, long believed to be dead, ha...","Walt-Disney-Pictures,Jerry-Bruckheimer-Films,S...","Johnny-Depp,Orlando-Bloom,Keira-Knightley,Stel...","Dariusz-Wolski,Gore-Verbinski,Jerry-Bruckheime..."
2,206647,"Action,Adventure,Crime","spy,based-on-novel,secret-agent,sequel,mi6,bri...",Spectre,A Plan No One Escapes,A cryptic message from Bond’s past sends him o...,"Columbia-Pictures,Danjaq,B24","Daniel-Craig,Christoph-Waltz,Léa-Seydoux,Ralph...","Thomas-Newman,Sam-Mendes,Anna-Pinnock,John-Log..."
3,49026,"Action,Crime,Drama,Thriller","dc-comics,crime-fighter,terrorist,secret-ident...",The Dark Knight Rises,The Legend Ends,Following the death of District Attorney Harve...,"Legendary-Pictures,Warner-Bros.,DC-Entertainme...","Christian-Bale,Michael-Caine,Gary-Oldman,Anne-...","Hans-Zimmer,Charles-Roven,Christopher-Nolan,Ch..."
4,49529,"Action,Adventure,Science-Fiction","based-on-novel,mars,medallion,space-travel,pri...",John Carter,"Lost in our world, found in another.","John Carter is a war-weary, former military ca...",Walt-Disney-Pictures,"Taylor-Kitsch,Lynn-Collins,Samantha-Morton,Wil...","Andrew-Stanton,Andrew-Stanton,John-Lasseter,Co..."
...,...,...,...,...,...,...,...,...,...
4798,9367,"Action,Crime,Thriller","united-states–mexico-barrier,legs,arms,paper-k...",El Mariachi,"He didn't come looking for trouble, but troubl...",El Mariachi just wants to play his guitar and ...,Columbia-Pictures,"Carlos-Gallardo,Jaime-de-Hoyos,Peter-Marquardt...","Robert-Rodriguez,Robert-Rodriguez,Robert-Rodri..."
4799,72766,"Comedy,Romance",,Newlyweds,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,,"Edward-Burns,Kerry-Bishé,Marsha-Dietlein,Caitl...","Edward-Burns,Edward-Burns,Edward-Burns,William..."
4800,231617,"Comedy,Drama,Romance,TV-Movie","date,love-at-first-sight,narration,investigati...","Signed, Sealed, Delivered",,"""Signed, Sealed, Delivered"" introduces a dedic...","Front-Street-Pictures,Muse-Entertainment-Enter...","Eric-Mabius,Kristin-Booth,Crystal-Lowe,Geoff-G...","Carla-Hetland,Harvey-Kahn,Adam-Sliwinski,Marth..."
4801,126186,,,Shanghai Calling,A New Yorker in Shanghai,When ambitious New York attorney Sam is sent t...,,"Daniel-Henney,Eliza-Coupe,Bill-Paxton,Alan-Ruc...","Daniel-Hsia,Daniel-Hsia"
4802,25975,Documentary,"obsession,camcorder,crush,dream-girl",My Date with Drew,,Ever since the second grade when he first saw ...,"rusty-bear-entertainment,lucky-crow-films","Drew-Barrymore,Brian-Herzlinger,Corey-Feldman,...","Clark-Peterson,Andrew-Reimer,Brian-Herzlinger,..."

In [24]:
#Lets concatenate all columns except id, title
# bcz i need to create a vector matrix, it will be easy to find unique words,stopwords etc from one column.
df['tags'] = df['genres'] + ',' +  df['keywords'] + ',' + df['tagline'] + ',' + df['overview'] + ',' + df['production_companies'] + ',' + df['cast'] + ',' + df['crew']

In [25]:
df

,id,genres,keywords,title,tagline,overview,production_companies,cast,crew,tags
0,19995,"Action,Adventure,Fantasy,Science-Fiction","culture-clash,future,space-war,space-colony,so...",Avatar,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...","Ingenious-Film-Partners,Twentieth-Century-Fox-...","Sam-Worthington,Zoe-Saldana,Sigourney-Weaver,S...","Stephen-E.-Rivkin,Rick-Carter,Christopher-Boye...","Action,Adventure,Fantasy,Science-Fiction,cultu..."
1,285,"Adventure,Fantasy,Action","ocean,drug-abuse,exotic-island,east-india-trad...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins.","Captain Barbossa, long believed to be dead, ha...","Walt-Disney-Pictures,Jerry-Bruckheimer-Films,S...","Johnny-Depp,Orlando-Bloom,Keira-Knightley,Stel...","Dariusz-Wolski,Gore-Verbinski,Jerry-Bruckheime...","Adventure,Fantasy,Action,ocean,drug-abuse,exot..."
2,206647,"Action,Adventure,Crime","spy,based-on-novel,secret-agent,sequel,mi6,bri...",Spectre,A Plan No One Escapes,A cryptic message from Bond’s past sends him o...,"Columbia-Pictures,Danjaq,B24","Daniel-Craig,Christoph-Waltz,Léa-Seydoux,Ralph...","Thomas-Newman,Sam-Mendes,Anna-Pinnock,John-Log...","Action,Adventure,Crime,spy,based-on-novel,secr..."
3,49026,"Action,Crime,Drama,Thriller","dc-comics,crime-fighter,terrorist,secret-ident...",The Dark Knight Rises,The Legend Ends,Following the death of District Attorney Harve...,"Legendary-Pictures,Warner-Bros.,DC-Entertainme...","Christian-Bale,Michael-Caine,Gary-Oldman,Anne-...","Hans-Zimmer,Charles-Roven,Christopher-Nolan,Ch...","Action,Crime,Drama,Thriller,dc-comics,crime-fi..."
4,49529,"Action,Adventure,Science-Fiction","based-on-novel,mars,medallion,space-travel,pri...",John Carter,"Lost in our world, found in another.","John Carter is a war-weary, former military ca...",Walt-Disney-Pictures,"Taylor-Kitsch,Lynn-Collins,Samantha-Morton,Wil...","Andrew-Stanton,Andrew-Stanton,John-Lasseter,Co...","Action,Adventure,Science-Fiction,based-on-nove..."
...,...,...,...,...,...,...,...,...,...,...
4798,9367,"Action,Crime,Thriller","united-states–mexico-barrier,legs,arms,paper-k...",El Mariachi,"He didn't come looking for trouble, but troubl...",El Mariachi just wants to play his guitar and ...,Columbia-Pictures,"Carlos-Gallardo,Jaime-de-Hoyos,Peter-Marquardt...","Robert-Rodriguez,Robert-Rodriguez,Robert-Rodri...","Action,Crime,Thriller,united-states–mexico-bar..."
4799,72766,"Comedy,Romance",,Newlyweds,A newlywed couple's honeymoon is upended by th...,A newlywed couple's honeymoon is upended by th...,,"Edward-Burns,Kerry-Bishé,Marsha-Dietlein,Caitl...","Edward-Burns,Edward-Burns,Edward-Burns,William...","Comedy,Romance,,A newlywed couple's honeymoon ..."
4800,231617,"Comedy,Drama,Romance,TV-Movie","date,love-at-first-sight,narration,investigati...","Signed, Sealed, Delivered",,"""Signed, Sealed, Delivered"" introduces a dedic...","Front-Street-Pictures,Muse-Entertainment-Enter...","Eric-Mabius,Kristin-Booth,Crystal-Lowe,Geoff-G...","Carla-Hetland,Harvey-Kahn,Adam-Sliwinski,Marth...","Comedy,Drama,Romance,TV-Movie,date,love-at-fir..."
4801,126186,,,Shanghai Calling,A New Yorker in Shanghai,When ambitious New York attorney Sam is sent t...,,"Daniel-Henney,Eliza-Coupe,Bill-Paxton,Alan-Ruc...","Daniel-Hsia,Daniel-Hsia",",,A New Yorker in Shanghai,When ambitious New ..."
4802,25975,Documentary,"obsession,camcorder,crush,dream-girl",My Date with Drew,,Ever since the second grade when he first saw ...,"rusty-bear-entertainment,lucky-crow-films","Drew-Barrymore,Brian-Herzlinger,Corey-Feldman,...","Clark-Peterson,Andrew-Reimer,Brian-Herzlinger,...","Documentary,obsession,camcorder,crush,dream-gi..."

In [26]:
df = df[['id', 'title', 'tags']]

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4803 non-null   int64
 1   title   4803 non-null   str
 2   tags    4803 non-null   str
dtypes: int64(1), str(2)
memory usage: 5.7 MB

In [28]:
df['tags'] = df['tags'].str.lower()

In [29]:
df.loc[0,'tags']

"action,adventure,fantasy,science-fiction,culture-clash,future,space-war,space-colony,society,space-travel,futuristic,romance,space,alien,tribe,alien-planet,cgi,marine,soldier,battle,love-affair,anti-war,power-relations,mind-and-soul,3d,enter the world of pandora.,in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.,ingenious-film-partners,twentieth-century-fox-film-corporation,dune-entertainment,lightstorm-entertainment,sam-worthington,zoe-saldana,sigourney-weaver,stephen-lang,michelle-rodriguez,giovanni-ribisi,joel-david-moore,cch-pounder,wes-studi,laz-alonso,dileep-rao,matt-gerald,sean-anthony-moran,jason-whyte,scott-lawrence,kelly-kilgour,james-patrick-pitt,sean-patrick-murphy,peter-dillon,kevin-dorman,kelson-henderson,david-van-horn,jacob-tomuri,michael-blain-rozgay,jon-curry,luke-hawker,woody-schultz,peter-mensah,sonia-yee,jahnel-curfman,ilram-choi,kyla-warren,lisa-roumain,debra-wilson,chris-mala,taylor-kibby,jodie-landau,julie-lamm,cullen-b.-madden,joseph-brady-madden,frankie-torres,austin-wilson,sara-wilson,tamica-washington-miller,lucy-briant,nathan-meister,gerry-blair,matthew-chamberlain,paul-yates,wray-wilson,james-gaylyn,melvin-leno-clark-iii,carvon-futrell,brandon-jelkes,micah-moch,hanniyah-muhammad,christopher-nolen,christa-oliver,april-marie-thomas,bravita-a.-threatt,colin-bleasdale,mike-bodnar,matt-clayton,nicole-dionne,jamie-harrison,allan-henry,anthony-ingruber,ashley-jeffery,dean-knowsley,joseph-mika-hunt,terry-notary,kai-pantano,logan-pithyou,stuart-pollock,raja,gareth-ruck,rhian-sheehan,t.-j.-storm,jodie-taylor,alicia-vela-bailey,richard-whiteside,nikie-zambo,julene-renee,stephen-e.-rivkin,rick-carter,christopher-boyes,christopher-boyes,mali-finn,james-horner,james-cameron,james-cameron,james-cameron,james-cameron,james-cameron,andrew-menzies,jill-brooks,margery-simkin,kevin-ishioka,dick-bernstein,shannon-mills,dennie-thorpe,jana-vance,deborah-lynn-scott,jon-landau,sean-haworth,kim-sinclair,kim-sinclair,richard-f.-mays,laeta-kalogridis,mayes-c.-rubeo,mauro-fiore,scott-herbertson,woody-schultz,linda-devetta,linda-devetta,richard-bluck,simon-bright,richard-martin,steve-r.-moore,john-refoua,karl-j.-martin,chiling-lin,ilram-choi,steven-quale,carla-meyer,nick-bassett,jill-cormack,andy-mclaren,terry-notary,garrett-warren,jonathan-rothbart,stefan-dechant,todd-cherniawsky,miranda-rivers,robert-stromberg,john-harding,roberto-de-angelis,mike-smithson,alain-lalanne,lucas-salton,janace-tashjian,stephen-rosenbaum,frankie-karena,lisa-lovaas,jonathan-fawkner,robert-bavin,anthony-almaraz,carolyn-m.-fenton,beth-koenigsberg,sam-page,tex-kadonaga,kim-foscato,tammy-s.-lee,denny-caira,james-waitkus,addison-teague,c.-scott-baker,luke-caska,david-chow,jonathan-dyer,joseph-hiura,rebecca-jellie,robert-andrew-johnson,mike-stassi,john-villarino,jeffrey-wisniewski,cheryl-nardi,marshall-winn,gwendolyn-yates-whittle,william-stein,lula-washington,chris-del-conte,r.-christopher-white,dan-lemmon,tim-nielsen,michael-mulholland,thomas-nittmann,edson-williams,christine-carr,john-bruno,david-emmerichs,christopher-scarabosio,jennifer-teves,brigitte-yorke,ken-fischer,iain-hutton,steve-ingram,joyce-cox,jenny-foster,christopher-marino,jim-milton,cyndi-ochs,lucas-putnam,anthony-'max'-ivins,john-knoll,eric-saindon,wayne-stables,david-stinnett,guy-williams,stuart-thorp,giles-coburn,mark-fellman,scott-sprague,jeremy-hollobon,orlando-meunier,taisuke-tanimura,lilia-mishel-acevedo,alejandro-m.-hernandez,marvin-hall,judy-alley,mike-perry,andrew-morley,seth-engstrom,eric-oliver,matsune-suzuki,paul-tobin,roxane-griffin,arun-ram-mohan,georgia-lockhart-adams,thrain-shadbolt,brad-alexander,shadi-almassizadeh,simon-clutterbuck,graeme-demmocks,adrian-fernandes,mitch-gates,jerry-kung,andy-lomas,sebastian-marino,matthias-menz,sergei-nevshupov,philippe-rebours,michael-takarangi,david-weitzberg,ben-white,min-windle"

In [30]:
# Cleaned data save
df.to_csv("cleaned_data.csv", index=False)